export const authConstansts = {
    USER_LOGIM_REQUEST: 'USER_LOGIM_REQUEST',
    USER_LOGIM_SUCCESS: 'USER_LOGIM_SUCCESS',
    USER_LOGIM_FAILURE: 'USER_LOGIM_FAILURE',

    USER_LOGOUT_REQUEST: 'USER_LOGOUT_REQUEST',
    USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
    USER_LOGOUT_FAILURE: 'USER_LOGOUT_FAILURE',
};

export const userConstants = {
    GET_REALTIME_USERS_REQUEST: 'GET_REALTIME_USERS_REQUEST',
    GET_REALTIME_USERS_SUCCESS: 'GET_REALTIME_USERS_SUCCESS',

    GET_REALTIME_MESSAGES_SUCCESS: 'GET_REALTIME_MESSAGES_SUCCESS',
    GET_REALTIME_MESSAGES_FAILURE: 'GET_REALTIME_MESSAGES_FAILURE',

    SUBMIT_DONUT_SUCCESS: 'SUBMIT_DONUT_SUCCESS',
};